[package]
name = "auditd-parser"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[dependencies]
anyhow = "1.0.97"
nom = "8.0.0"
serde = { version = "1.0.218", features = ["derive"], optional = true }

[features]
default = ["serde"]
serde = ["dep:serde"]
