//! Linux kernel constants generated from kernel headers using bindgen.
//! 
//! This module provides type-safe access to Linux kernel constants such as:
//! - Signal numbers (SIGHUP, SIGINT, etc.)
//! - Architecture definitions (EM_*, AUDIT_ARCH_*)
//! - Socket address families (AF_UNIX, AF_INET, etc.)
//! - File mode and stat constants (S_IF*, S_I*)
//!
//! These constants are automatically generated at build time from the system's
//! kernel headers, ensuring they stay up-to-date with the kernel version.

#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(non_snake_case)]
#![allow(dead_code)]

// Include the bindings generated by bindgen at build time
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
